# Generated by Django 3.1 on 2020-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200812_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doviz_ismi', models.CharField(max_length=10)),
                ('alis', models.FloatField()),
                ('satis', models.FloatField()),
                ('fark', models.FloatField()),
                ('kur_kodu', models.CharField(max_length=10)),
            ],
        ),
    ]
